(ux-improvements) New: address book, fee, confirm intention, view of notifications
stellar-expert/albedo pull request #90
Opened 2023-08-05 07:28 UTC by yazadzhy

2023-08-16 14:21 UTC, orbitlens requested changes

2023-08-16 14:21 UTC, orbitlens commented on frontend/src/ui/wallet/transfer/destination-hints-view.js
> +    const destinationIsOwnAccount = toJS(accountManager.accounts).findIndex(account => account.publicKey.startsWith(destination)) !== -1
```suggestion
    const destinationIsOwnAccount = accountManager.accounts.some(account => account.publicKey.startsWith(destination))
```

2023-08-16 14:21 UTC, orbitlens commented on frontend/src/ui/wallet/transfer/destination-hints-view.js
> +    }, [transfer, title])
Not a good idea. The callback will be recreated each time title changes.

2023-08-16 14:21 UTC, orbitlens commented on frontend/src/ui/wallet/transfer/transfer-tx-builder.js
> +        fee: (['low', 'normal', 'high'].includes(transfer.fee)) ? await estimateFee(transfer.network, transfer.fee) : transfer.fee
👍

2023-08-16 14:21 UTC, orbitlens commented on frontend/src/ui/wallet/transfer/transfer-view.js
> +    const cancelDestinationCreation = useCallback(() => runInAction(() => transfer.createDestination = false), [transfer])
```suggestion
    const cancelDestinationCreation = useCallback(() => runInAction(() => {
        transfer.createDestination = false
    }), [transfer])
```

2023-08-16 14:21 UTC, orbitlens commented on frontend/src/util/account-notifications.js
> +            }).catch(e => console.log(e))
```suggestion
            }).catch(e => console.error(e))
```

2023-08-16 14:21 UTC, orbitlens commented on frontend/src/util/fee-estimator.js
👍

2023-08-16 14:21 UTC, orbitlens commented on frontend/src/util/get-federation-address.js
This functionality duplicates `frontend/src/util/federation-address-resolver.js`

2023-08-17 12:10 UTC, yazadzhy commented on frontend/src/ui/authentication/credentials-request-view.js
> +    const confirm = useCallback(() => {
`password` deleted from dependencies and all works like usually, but if delete `updateState` - doesn't work, seems cached empty password from default value, i'll check more deeply

2023-08-17 15:41 UTC, yazadzhy commented on frontend/src/ui/notifications/notifications.js
> +            <div className="lifetime" style={{animationDuration: timeToClose + 'ms'}}/>
Pausing of animation declared in CSS on :hover - it works with hover, selection of text, click on notification. I tested logic and visualization - all work correctly

2023-08-17 17:59 UTC, yazadzhy commented on frontend/src/ui/notifications/notifications.js
> +        notification.current.addEventListener("mouseover", pauseTimer, true)
i tried it firstly, but not fully work like needed, but now all works correctly, strange, mb used wrong logic before

2023-08-30 18:17 UTC, orbitlens approved these changes

2023-08-30 18:18 UTC, merged